name: cal_easy
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 8.0.2+31

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # 追加
    sdk: flutter # 追加
  common:
    path: ../common
  quiz:
    path: ../quiz
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.8
  path_provider: ^2.0.11 # path_providerパッケージを追加
  flutter_math_fork: ^0.7.2
  logger: ^2.6.1
  math_expressions:
  petitparser:
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  just_audio: ^0.10.4
  provider: ^6.1.5
  google_mobile_ads: ^5.0.0
  firebase_crashlytics: ^5.0.0
  intl: ^0.20.2
  hooks_riverpod: ^2.6.1
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.0 # ストアを開く用
  audioplayers: ^6.6.0
  visibility_detector: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  rename: ^3.0.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "packages/common/asset/cal_easy.png"
