// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPEBv_Ak703iUthgx0ctA4l1SgNzsFGjM',
    appId: '1:109841804761:web:e7e834b777d51d6bfcfdc8',
    messagingSenderId: '109841804761',
    projectId: 'highlymathquiz',
    authDomain: 'highlymathquiz.firebaseapp.com',
    storageBucket: 'highlymathquiz.firebasestorage.app',
    measurementId: 'G-DLXBWBKR3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChYRFXhPs1v_pwErVLyysjk1y--U_2pvM',
    appId: '1:109841804761:android:73ae6c4fbe1ecb36fcfdc8',
    messagingSenderId: '109841804761',
    projectId: 'highlymathquiz',
    storageBucket: 'highlymathquiz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBKApdmrXoRosRQfFNPfrwh84cBrlieIY',
    appId: '1:109841804761:ios:e87b1c019dd67575fcfdc8',
    messagingSenderId: '109841804761',
    projectId: 'highlymathquiz',
    storageBucket: 'highlymathquiz.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBKApdmrXoRosRQfFNPfrwh84cBrlieIY',
    appId: '1:109841804761:ios:e87b1c019dd67575fcfdc8',
    messagingSenderId: '109841804761',
    projectId: 'highlymathquiz',
    storageBucket: 'highlymathquiz.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPEBv_Ak703iUthgx0ctA4l1SgNzsFGjM',
    appId: '1:109841804761:web:d066d0dceba49870fcfdc8',
    messagingSenderId: '109841804761',
    projectId: 'highlymathquiz',
    authDomain: 'highlymathquiz.firebaseapp.com',
    storageBucket: 'highlymathquiz.firebasestorage.app',
    measurementId: 'G-M45ZK7CHFG',
  );

}