// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwWo_wHwWK0nT8UpeQqMobES1Fqfqm9ec',
    appId: '1:870670936618:web:1a51b374a0d5136a193153',
    messagingSenderId: '870670936618',
    projectId: 'reflect-ponta',
    authDomain: 'reflect-ponta.firebaseapp.com',
    storageBucket: 'reflect-ponta.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV7W5x9H5LoaV4eN1PyMxYBV70sJKlua4',
    appId: '1:870670936618:android:21af3e9ab854bca3193153',
    messagingSenderId: '870670936618',
    projectId: 'reflect-ponta',
    storageBucket: 'reflect-ponta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKeWxrfC9M6iXxnRz3ghg6Fs7hllMyDpQ',
    appId: '1:870670936618:ios:bab5ba4c54e3f2cf193153',
    messagingSenderId: '870670936618',
    projectId: 'reflect-ponta',
    storageBucket: 'reflect-ponta.firebasestorage.app',
    iosBundleId: 'jp.ponta.reflect',
  );
}
